export default interface Inventory {
    fuel: number,
    maxFuel: number,
    money: number,
    matter: number,
    water: number,
    flora: number,
    minerals: number,
    fauna: number,
    fungi: number,
    energy: number,
    wisdom: number,
    weaponry: number,
    technology: number,
    maxCargo: number,
    hull: number,
    maxHull: number,
    ammo: number,
    maxAmmo: number
}